#!/usr/bin/python3
import time
from monisys.Managers.Systeminfo import SystemInfo
system_info = SystemInfo('docker_images')

cpuinfo = system_info.get_all_data()

# print(len(cpuinfo))
for i in range(int(len(cpuinfo))):
    print(cpuinfo[i])